version: "3.7"

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 7002:5432
    environment:
      - POSTGRES_USER=$DOCKER_USERNAME
      - POSTGRES_PASSWORD=$DOCKER_PASSWORD
      - POSTGRES_DB=$DOCKER_DATABASE
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: rentx
  #   links:
  #     - database_rentx
  #   depends_on:
  #     - database_rentx
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/user/app

volumes:
  pgdata:
    driver: local
